### ISSUE TITLE
Feature: append to lists

### ISSUE THREAD

**Issue by rstacruz** [egoist/update-pkg#1]
It'd be nice to append to lists.

```js
pkg.append('keywords', 'hello')
pkg.append('babel.presets', 'react')
```

On that note, it'd be nice to have an update function that updates a certain key:

```js
pkg.update('license', lic => lic || 'MIT')
```

so `.append` is now simply syntactic sugar for update:

```js
pkg.append = (key, value) => pkg.update(key, oldValue => (oldValue || []).concat(value))

**Comment by egoist** [comment]
nice idea 👍

**Comment by rstacruz** [comment]
Nice one dude! ~~I think you mispelt `prepend` though~~ EDIT: fixed!
